# Generated by Django 2.2.5 on 2019-09-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0002_auto_20190915_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valor_cotaçãomodels',
            name='cotacao',
        ),
        migrations.AddField(
            model_name='valor_cotaçãomodels',
            name='cotacao',
            field=models.ManyToManyField(to='comparador.PousadaModels'),
        ),
    ]
