# Generated by Django 2.2.5 on 2019-10-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0003_auto_20190915_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valor_cotaçãomodels',
            name='cotacao',
        ),
        migrations.AddField(
            model_name='valor_cotaçãomodels',
            name='cotacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comparador.PousadaModels'),
            preserve_default=False,
        ),
    ]
