# Generated by Django 2.1.5 on 2019-02-23 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pousada', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('check_in', models.DateField(blank=True)),
                ('check_out', models.DateField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('n_pessoas', models.IntegerField()),
                ('valor_disconto', models.IntegerField()),
                ('val_diaria', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CasadePedraCotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField(blank=True)),
                ('person_num', models.IntegerField(blank=True)),
                ('discount', models.IntegerField(blank=True)),
                ('discount_dialy', models.IntegerField(blank=True)),
                ('dialy_of_price', models.FloatField(blank=True)),
                ('portion', models.IntegerField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
