# Generated by Django 2.1.5 on 2019-01-24 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 4, 18, 57, 249536)),
        ),
    ]
