# Generated by Django 2.1.5 on 2019-02-24 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0003_auto_20190223_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casadepedracotacao',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
