# Generated by Django 2.1.5 on 2019-01-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0004_auto_20190124_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
