# Generated by Django 2.1.5 on 2019-02-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0004_auto_20190224_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casadepedracotacao',
            name='portion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
