# Generated by Django 2.1.5 on 2019-01-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0005_auto_20190124_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='lastname',
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
