# Generated by Django 2.1.5 on 2019-01-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0007_auto_20190124_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='n_pessoas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='nome',
            field=models.CharField(max_length=252),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='valor_disconto',
            field=models.IntegerField(),
        ),
    ]
