# Generated by Django 2.1.5 on 2019-01-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0008_auto_20190126_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
