# Generated by Django 2.1.5 on 2019-01-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0009_auto_20190126_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
