# Generated by Django 2.1.5 on 2019-01-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0010_auto_20190126_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='check_in',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='check_out',
            field=models.DateField(blank=True),
        ),
    ]
