# Generated by Django 2.1.5 on 2019-01-29 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0012_auto_20190128_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='date1',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='date2',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
