# Generated by Django 2.1.5 on 2019-01-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0013_auto_20190129_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='blogcomments',
            name='date2',
        ),
    ]
