# Generated by Django 2.1.5 on 2019-01-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0014_auto_20190130_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='diarias',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='val_diarias',
            field=models.FloatField(default=(290, 90)),
            preserve_default=False,
        ),
    ]
