# Generated by Django 2.1.5 on 2019-05-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0007_auto_20190224_0901'),
        ('pousada', '0016_auto_20190528_1622'),
    ]

    operations = [
    ]
