# Generated by Django 2.2.6 on 2019-10-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotaçõeshospedemodels',
            name='valor',
        ),
        migrations.AddField(
            model_name='textowhatsappmodels',
            name='check_in',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='textowhatsappmodels',
            name='check_out',
            field=models.DateField(default=None),
        ),
    ]
