# Generated by Django 2.2.4 on 2019-09-11 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('check_in', models.DateField(blank=True)),
                ('check_out', models.DateField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('n_pessoas', models.IntegerField()),
                ('valor_disconto', models.IntegerField()),
                ('val_diaria', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CasadePedraCotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('person_num', models.IntegerField()),
                ('kidquestion', models.CharField(max_length=3)),
                ('kidyears', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dialy_of_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('portion', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dialy_of_price_site', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CasadePedraFicha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birdth', models.DateField()),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('neighborhood', models.TextField()),
                ('cep', models.CharField(max_length=8)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('profession', models.TextField()),
                ('email', models.CharField(max_length=30)),
                ('vehicle', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('namecotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pousada.CasadePedraCotacao')),
            ],
        ),
    ]
